function xlsxPath = create_dd_template(SWCName, rootDir)
% create_dd_template 新建数据字典Excel模板（V2：Input/Output/Calibration显式区分）
%   手填主入口：Input / Output / Calibration；Interface/Port为对照视图（由前三者推导，勿单独手改）
if nargin < 2 || isempty(rootDir)
    rootDir = fileparts(mfilename('fullpath'));
    rootDir = fileparts(rootDir); % VCU_AppTool根
end
ddDir = fullfile(rootDir, '02_dd');
if ~exist(ddDir, 'dir'), mkdir(ddDir); end
xlsxPath = fullfile(ddDir, [SWCName '_dd.xlsx']);
if exist(xlsxPath, 'file'), delete(xlsxPath); end

info = {'Item','Value'; ...
    'SWCName',SWCName; ...
    'Version','0.2'; ...
    'AutosarSchema','4.4'; ...
    'Author',''; ...
    'Date',char(datetime('today','Format','yyyy-MM-dd')); ...
    'ChangeLog','V2: Input/Output/Calibration显式分表'};
writecell(info, xlsxPath, 'Sheet', 'Info');

dt = {'Name','BaseType','Unit','Min','Max','Init','Desc'; ...
    'VehSpd','single','km/h',0,300,0,'vehicle speed'; ...
    'DrvTrqReq','single','Nm',-500,2000,0,'driver torque request'};
writecell(dt, xlsxPath, 'Sheet', 'DataType');

en = {'EnumName','Value','Text','Desc'; ...
    'En_DrvMode',0,'ECO','eco mode'; ...
    'En_DrvMode',1,'NORMAL','normal'; ...
    'En_DrvMode',2,'SPORT','sport'};
writecell(en, xlsxPath, 'Sheet', 'Enum');

% --- 主入口三表：输入 / 输出 / 标定 ---
inp = {'SignalName','Port','Interface','DataType','Unit','Min','Max','Init','Desc'; ...
    'In_VehSpd','P_VehSpd','If_VehSpd','VehSpd','km/h',0,300,0,'vehicle speed input'; ...
    'In_DrvMode','P_DrvMode','If_DrvMode','En_DrvMode','none',0,2,1,'driver mode input'};
writecell(inp, xlsxPath, 'Sheet', 'Input');

out = {'SignalName','Port','Interface','DataType','Unit','Min','Max','Init','Desc'; ...
    'Out_DrvTrqReq','P_DrvTrqReq','If_DrvTrqReq','DrvTrqReq','Nm',-500,2000,0,'torque request output'};
writecell(out, xlsxPath, 'Sheet', 'Output');

cal = {'CalibName','DataType','Unit','Min','Max','Init','Desc'; ...
    'Cal_TrqMax','single','Nm',0,2000,1500,'max torque cal'; ...
    'Cal_TrqRate','single','Nm/s',0,5000,2000,'torque rate limit cal'};
writecell(cal, xlsxPath, 'Sheet', 'Calibration');

% --- 对照视图（由Input/Output推导，保持一致即可）---
iface = {'Interface','IFType','DataType','Dim','Desc'; ...
    'If_VehSpd','SR','VehSpd',1,'from Input In_VehSpd'; ...
    'If_DrvMode','SR','En_DrvMode',1,'from Input In_DrvMode'; ...
    'If_DrvTrqReq','SR','DrvTrqReq',1,'from Output Out_DrvTrqReq'};
writecell(iface, xlsxPath, 'Sheet', 'Interface');

port = {'Port','Dir','Interface','SignalName','Desc'; ...
    'P_VehSpd','In','If_VehSpd','In_VehSpd','require speed'; ...
    'P_DrvMode','In','If_DrvMode','In_DrvMode','require mode'; ...
    'P_DrvTrqReq','Out','If_DrvTrqReq','Out_DrvTrqReq','provide torque'};
writecell(port, xlsxPath, 'Sheet', 'Port');

run = {'Runnable','Period_ms','TrigPort','AccessedPorts','Desc'; ...
    ['R_' SWCName '_10ms'],10,'TimingEvent','P_VehSpd;P_DrvMode;P_DrvTrqReq','main runnable'};
writecell(run, xlsxPath, 'Sheet', 'Runnable');

sig = {'Name','Kind','DataType','Init','Desc','SrcBlock'; ...
    'Irv_TrqLim','IRV','DrvTrqReq',0,'internal torque limit',''; ...
    'Meas_TrqOut','Meas','DrvTrqReq',0,'measurement for cal',''};
writecell(sig, xlsxPath, 'Sheet', 'Signal_NVM');

fprintf('模板已生成(V2): %s\n', xlsxPath);
end
