function make_icons(iconDir)
% make_icons 生成工具栏图标（16/24px PNG）：色块分区+双字母，免依赖外部图
%   用法: make_icons（默认写 resources/icons/）
if nargin < 1 || isempty(iconDir)
    iconDir = fullfile(fileparts(mfilename('fullpath')), 'resources', 'icons');
end
if ~exist(iconDir,'dir'), mkdir(iconDir); end
% {actionId, 文字, 背景RGB}
defs = {
    'vcuOpenApp', 'Ap', [ 41  98 255]; ...
    'vcuNewSwc',  'N+', [ 41  98 255]; ...
    'vcuDdGen',   'Xl', [ 52 168  83]; ...
    'vcuDdCheck', 'Ck', [ 52 168  83]; ...
    'vcuCodegen', 'C+', [237 125  49]; ...
    'vcuArxml',   'Xm', [237 125  49]; ...
    'vcuA2l',     'A2', [237 125  49]; ...
    'vcuRunAll',  '>>', [136  77 255]; ...
    'vcuTest',    'Ts', [136  77 255]; ...
    };
for k = 1:size(defs,1)
    id = defs{k,1}; txt = defs{k,2}; bg = defs{k,3};
    big = uint8(zeros(96, 96, 3));
    for c = 1:3, big(:,:,c) = bg(c); end
    big = insertText(big, [48 48], txt, 'FontSize', 56, ...
        'BoxOpacity', 0, 'TextColor', 'white', 'AnchorPoint', 'Center');
    for sz = [16 24]
        imwrite(imresize(big, [sz sz]), fullfile(iconDir, sprintf('%s_%d.png', id, sz)));
    end
end
fprintf('图标已生成(%d套): %s\n', size(defs,1), iconDir);
end
